version: 3

# Configure Images
images:
  base_image:
    name: quay.io/ansible/awx-ee:24.6.1

# Dependencies
dependencies:
  python: requirements.txt
  galaxy: requirements.yml
  system: requirements-os.txt

# Additional Steps
additional_build_steps:
  append_base: |
    RUN $PYCMD -m pip install -U pip==23.3 setuptools==70.0.0
