roles:
  - name: kubecloud.consul-config-loader
    src: https://github.com/kube-cloud/kc-is-sre-ansible-role-consul-config-loader
    version: 1.0.0
  - name: kubecloud.vault-secrets-loader
    src: https://github.com/kube-cloud/kc-is-sre-ansible-role-vault-secrets-loader
    version: 1.0.0

collections:
  - name: community.general
  - name: community.crypto
  - name: awx.awx
  - name: azure.azcollection
    version: ">=2.1.0"
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
  - name: kubevirt.core
